// // Integration starter, not an already integrated or device-tested application.
// // Reuse the project's existing Dio instance and secure token storage.
// import 'package:dio/dio.dart';
// import 'consumer_endpoints.dart';

// class ConsumerApiError implements Exception {
//   final int? statusCode;
//   final String message;
//   final List<dynamic> errorSources;
//   const ConsumerApiError(this.statusCode, this.message,
//       [this.errorSources = const []]);
//   @override
//   String toString() => message;
// }

// class ConsumerResponse {
//   final dynamic data;
//   final Map<String, dynamic>? meta;
//   final String message;
//   const ConsumerResponse(this.data, this.meta, this.message);

//   factory ConsumerResponse.fromJson(Map<String, dynamic> json) {
//     if (json['success'] != true) {
//       throw ConsumerApiError(
//         (json['statusCode'] as num?)?.toInt(),
//         json['message']?.toString() ?? 'Request failed',
//         json['errorSources'] is List ? json['errorSources'] as List : [],
//       );
//     }
//     return ConsumerResponse(
//       json['data'],
//       json['meta'] is Map
//           ? Map<String, dynamic>.from(json['meta'] as Map)
//           : null,
//       json['message']?.toString() ?? '',
//     );
//   }

//   Map<String, dynamic> object() {
//     if (data is! Map) throw const FormatException('Expected data object');
//     return Map<String, dynamic>.from(data as Map);
//   }

//   List<Map<String, dynamic>> list() => mapList(data);
//   List<Map<String, dynamic>> featureList() => mapList(object()['data']);

//   static List<Map<String, dynamic>> mapList(dynamic value) {
//     if (value is! List) throw const FormatException('Expected data array');
//     return value.map((item) {
//       if (item is! Map) throw const FormatException('Expected array item object');
//       return Map<String, dynamic>.from(item);
//     }).toList();
//   }
// }

// class ConsumerApi {
//   final Dio dio;
//   final Future<String?> Function() readAccessToken;
//   final String baseUrl;
//   final bool allowZipOnly;

//   ConsumerApi({
//     required this.dio,
//     required this.readAccessToken,
//     this.baseUrl = 'https://api.humidor411.com/api/v1',
//     this.allowZipOnly = false,
//   });

//   Future<ConsumerResponse> call(
//     String key, {
//     Map<String, String> variables = const {},
//     Map<String, dynamic> query = const {},
//     dynamic body,
//     bool sendOptionalCustomerToken = false,
//     CancelToken? cancelToken,
//   }) async {
//     final endpoint = consumerEndpoints[key];
//     if (endpoint == null) throw ArgumentError('Unknown API key: $key');
//     if (endpoint.zipOnly && !allowZipOnly) {
//       throw StateError('Confirm deployed ZIP guided API before enabling it');
//     }
//     final route = endpoint.route.replaceAllMapped(
//       RegExp(r'\{\{([a-zA-Z0-9]+)\}\}'),
//       (match) {
//         final value = variables[match.group(1)];
//         if (value == null) {
//           throw ArgumentError('Missing URL variable: ${match.group(1)}');
//         }
//         return Uri.encodeComponent(value);
//       },
//     );
//     final templateUri = Uri.parse('${baseUrl.replaceFirst(RegExp(r'/+$'), '')}$route');
//     final params = <String, String>{...templateUri.queryParameters};
//     for (final entry in query.entries) {
//       if (entry.value == null) {
//         params.remove(entry.key);
//       } else {
//         params[entry.key] = entry.value.toString();
//       }
//     }
//     final uri = templateUri.replace(queryParameters: params.isEmpty ? null : params);
//     final token = endpoint.requiresCustomer || sendOptionalCustomerToken
//         ? await readAccessToken()
//         : null;
//     if (endpoint.requiresCustomer && (token == null || token.isEmpty)) {
//       throw const ConsumerApiError(401, 'Please sign in');
//     }
//     try {
//       final response = await dio.request<dynamic>(
//         uri.toString(),
//         data: body,
//         cancelToken: cancelToken,
//         options: Options(
//           method: endpoint.method,
//           // Multipart boundary is generated by Dio.
//           contentType: body is FormData ? null : Headers.jsonContentType,
//           headers: {
//             'Accept': 'application/json',
//             if (token != null && token.isNotEmpty)
//               'Authorization': 'Bearer $token',
//           },
//         ),
//       );
//       if (response.data is! Map) {
//         throw const FormatException('Expected response envelope object');
//       }
//       return ConsumerResponse.fromJson(
//           Map<String, dynamic>.from(response.data as Map));
//     } on DioException catch (error) {
//       if (error.type == DioExceptionType.cancel) rethrow;
//       final payload = error.response?.data;
//       throw ConsumerApiError(
//         error.response?.statusCode,
//         payload is Map
//             ? payload['message']?.toString() ?? 'Request failed'
//             : 'Connection failed; please retry',
//         payload is Map && payload['errorSources'] is List
//             ? payload['errorSources'] as List
//             : [],
//       );
//     }
//   }
// }

// // Master references are string IDs in writes, populated objects in some reads.
// String? referenceId(dynamic value) {
//   if (value is String) return value;
//   if (value is Map) return (value['_id'] ?? value['id'])?.toString();
//   return null;
// }

// double? nullableMoney(dynamic value) => value is num ? value.toDouble() : null;

// class ProductContext {
//   final String masterCigarId;
//   final String? inventoryId;
//   final String? retailerId;
//   final String? storeSlug;
//   const ProductContext({
//     required this.masterCigarId,
//     this.inventoryId,
//     this.retailerId,
//     this.storeSlug,
//   });
// }
